// <auto-generated />
namespace IT_Assistant_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addses));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240127570_addses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
