// <auto-generated />
namespace IT_Assistant_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Location2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Location2));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091824554_Location2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
